name: Bug Report
description: Report a bug or issue with Tread
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., macOS 14.2, Ubuntu 24.04, Arch Linux"
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal Emulator
      description: What terminal are you using?
      placeholder: "e.g., iTerm2 3.5, Alacritty 0.13, Kitty 0.32"
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun Version
      description: Output of `bun --version`
      placeholder: "e.g., 1.3.3"
    validations:
      required: true

  - type: input
    id: tread-version
    attributes:
      label: Tread Version
      description: Output of `tread --version` or commit hash if built from source
      placeholder: "e.g., 0.4.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start tread with '...'
        2. Navigate to '...'
        3. Press '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: |
        If applicable, add logs (run with `TREAD_LOG_LEVEL=debug`) or screenshots.
      placeholder: |
        ```
        Paste logs here
        ```

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        If relevant, share your `~/.config/tread/config.toml` (remove any sensitive data).
      placeholder: |
        ```toml
        Paste config here
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
