name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: "It would be great if Tread could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: What part of Tread does this relate to?
      options:
        - UI / Display
        - Keyboard Navigation
        - Feed Management
        - Article Reading
        - Configuration
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
